package:
  name: tethys_dataset_services
  version: "2.0.1"

source:
  git_rev: 2.0.1
  git_url: https://github.com/tethysplatform/tethys_dataset_services.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - gsconfig
    - django
    - future
    - owslib
    - requests
    - requests-toolbelt
    - coverage
    - sqlalchemy
    - psycopg2

build:
  noarch: python

test:
  imports:
    - tethys_dataset_services
    - tethys_dataset_services.engines

about:
  home: https://github.com/tethysplatform/tethys_dataset_services
  license: 'BSD 2-Clause "Simplified" License'
  license_file: LICENSE